config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  get 'welcome/index'

  root 'albums#index'

  resources :albums do
    resources :pictures
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :pictures, dependent: :destroy
  
  validates :name, presence: true,
              length: { minimum: 5 }
  belongs_to :author
    
 
end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :albums
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album  
  has_attached_file :image, :styles => {medium: "300x300>", thumb: "100x100>"}
  do_not_validate_attachment_file_type :image

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums=current_author.albums.paginate(:page => params[:page], :per_page =>4)
  end
  def new
    @album=Album.new
  end
  def show
    @album = Album.find(params[:id])
    end

  def create
    @album = Album.new(album_params)
    if @album.save 
    redirect_to @album
    else
      render 'new'
    end
end
  
  def destroy
      @album=Album.find(params[:id])
      @album.destroy
      redirect_to albums_path
    
  end

private
  def album_params
    params.require(:album).permit(:name,:author_id)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    before_action :authenticate_author!

  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @album=Album.find(params[:album_id])
    @picture=@album.pictures.all

  end
  def new
     @album = Album.find(params[:album_id])
  end

  
  def show 
    @album=Album.find(params[:album_id])
    @picture=@album.pictures.find(params[:id])
  end
  
  def edit 
    @album=Album.find(params[:album_id])
    @picture=@album.pictures.find(params[:id])
  end
  
  def create
    @album=Album.find(params[:album_id])
    @picture=@album.pictures.create(picture_params)
    redirect_to album_path(@album)
  end
   def update
     @album=Album.find(params[:album_id])
    @picture=@album.pictures.find(params[:id])
    if @picture.update(picture_params)
      redirect_to album_path(@album)
    else
      render 'edit'
    end
  end

  def destroy
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.find(params[:id])
    @picture.destroy
    redirect_to album_path(@album)
  end
  
  private
    def picture_params
      params.require(:picture).permit(:name,:image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/album_imgs_helper.rb
module AlbumImgsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_for @album do |f| %>

 <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@album.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
        <%= f.hidden_field :author_id, value: current_author.id %>

  </p>
  <p>
    <%= f.submit %><br>
  </p>
<% end %>

app/views/albums/index.html.erb
<h1>It's album index file</h1>

 <%= link_to 'New Album', new_album_path %>
<table border="2">
  <tr>
    <th colspan="3"><h2>Albums</h2></th>
  </tr>
  <% @albums.each do |album| %>
 
      <td><%= link_to "#{image_tag (album.pictures.last.image.url(:medium))}".html_safe, album_path(album) %></td>
      <td><%= album.name %></td>
      
<td><a href="<%= album_path(album)%>" data-confirm="Are you sure?" data-method="delete">Destroy Album</a>       
 </td></tr>
  

<%end%>
</table>
<%= will_paginate @albums %>

app/views/albums/new.html.erb
<h1>Welcome to new album file</h1>
<%= render 'form' %>
<%= link_to 'All Albums', albums_path %>

app/views/albums/show.html.erb
<p>
  <strong>Album Name:</strong>
  <%= @album.name %>
</p>
    
<h2>Add a Album Images:</h2>
<% if @album.pictures %>
  <%= render @album.pictures %>
<% end %> 
<input type="button" class="add_picture" value="Add_picture">
<div class="picture_form" style="display:none;"><%= render 'pictures/form' %>
 </div>
 <%= link_to 'Back',new_album_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%=link_to 'Logout', destroy_author_session_path, method: :delete%>

<%= yield %>

</body>
</html>

app/views/pictures/===show.html.erb
<table>
  <tr>
    <th>Image</th>
    <th>Name</th>
  </tr>
 
  <%  @album.pictures .each do |picture| %>
    <tr>
      <td> <%= image_tag picture.image.url(:medium)%></td>
      <td><%= picture.name %></td>
 <td> <a href="<%= album_picture_path(picture.album, picture)%>" data-confirm="Are you sure?" data-method="delete">Destroy Comment</a></td>

    </tr>
  <% end %>
</table>

app/views/pictures/_form.html.erb
<% form_url = @picture.present? ?  album_picture_path(@album,@picture) : album_pictures_path(@album)  %>

<% @picture = @picture.present? ? @picture : @album.pictures.new %>
<%= form_for @picture, url: form_url ,:html => { :multipalrt => true } do |f| %>
  <p>
    <%= f.label :album_add %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :AlbumimageName %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pictures/_picture.html.erb
<%= image_tag picture.image.url(:medium)%>

<p>
  <strong>Picture:</strong>
  <%= picture.name %>
</p>
<p>
  <%= link_to 'Edit',edit_album_picture_path(@album,picture)%>
 
  <a href="<%= album_picture_path(picture.album, picture)%>" data-confirm="Are you sure?" data-method="delete">Destroy Picture</a>
</p>

app/views/pictures/edit.html.erb
<h1>Editing page Pictures</h1>
<%= render 'form' %>
 
<%= link_to 'Back', album_picture_path %>

app/views/pictures/index.html.erb
<h1>Index page Picture</h1>
<table>
  <tr>
    <% @picture.each do |picture| %>
    <td> <%= image_tag picture.image.url(:medium)%></td>
    <td><%= picture.name %></td>
    <td> <a href="<%= album_picture_path(@album,picture)%>" data-confirm="Are you sure?" data-method="delete">Destroy Comment</a>
    </td>
  </tr>
    <% end %>
</table>

  

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
 <%= link_to 'New Album', new_album_path %>